import PokemonList from "./components/PokemonList";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {

  return (
    <div className="font-sans items-center justify-items-center min-h-screen p-8 pb-20 sm:p-20">
      <header className="row-start-1 text-center mb-10">
        <h1 className="text-1xl font-bold font-sans text-gray-500">Actividad 6 - Sistemas Distribuidos</h1>
        <h1 className="text-4xl font-extrabold font-sans text-blue-700 mt-2">Seleccione un Pokémon</h1>
      </header>
      <main className="container mx-auto">
        {/* Llama al componente cliente que iniciará la carga de datos */}
        <PokemonList/>
      </main>
    </div>
  );
}